### ISSUE TITLE
Invalid url

### ISSUE THREAD

**Issue by linux21123** [Shaveyy/TwitchSpam#71]
I can't use the Stream command everytime comes invalid URL and if i use followbot comes nothing in the terminal massiv errors

**Comment by linux21123** [comment]
Exception in thread Thread-67:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/TwitchSpam/twitchspam/follow.py", line 18, in follow_channel
    token = f[i].split(":")[2]
IndexError: list index out of range
Exception in thread Thread-24:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/root/TwitchSpam/twitchspam/follow.py", line 18, in follow_channel
    token = f[i].split(":")[2]
IndexError: list index out of range

**Comment by Shaveyy** [comment]
The OAuth file your using has an invalid format. I'd close this, but the format the program accepts is sort of incorrect so I'll  release a patch that fixes this.
